### ISSUE TITLE
Doc links on the readme dead

### ISSUE THREAD

**Issue by ablaom** [TuringLang/ParetoSmooth.jl#15]
Currently these are working for me.

**Comment by ablaom** [comment]
Oh I see. Nothing has been generated yet.

**Comment by ParadaCarleton** [comment]
@ablaom Hi -- not sure what you mean, could you clarify?

**Comment by ablaom** [comment]
I clicked on the documentation badge on the readme but that link is broken, presumable because there is not documentation yet, right?

**Comment by ParadaCarleton** [comment]
Yep, that's correct.

**Comment by ParadaCarleton** [comment]
Fixed by Mohamed in #33
