### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/ParetoSmooth.jl#31]
We should get CI set up and working with Turing's. Not 100% sure how, but I'll need to get it done :sweat_smile:

**Comment by ParadaCarleton** [comment]
@rikhuijzer Jose Storopoli mentioned you might be able to help with this?

**Comment by rikhuijzer** [comment]
I'm sorry, @ParadaCarleton. The timing is quite bad now. I'm for a week on the road for my PhD. In general, to develop CI quickly, I would advise to create a new branch for each feature and just send in many commits and check the log output. Once the feature work, squash the commits.

Let me know if you have a specific question, but know that I'm unlikely to respond this week.

**Comment by ParadaCarleton** [comment]
> I'm sorry, @ParadaCarleton. The timing is quite bad now. I'm for a week on the road for my PhD. In general, to develop CI quickly, I would advise to create a new branch for each feature and just send in many commits and check the log output. Once the feature work, squash the commits.
> 
> Let me know if you have a specific question, but know that I'm unlikely to respond this week.

No worries! We can discuss it later.
