### ISSUE TITLE
TuringHelpers docstrings have unresolved conflicts

### ISSUE THREAD

**Issue by sethaxen** [TuringLang/ParetoSmooth.jl#49]
TuringHelpers.jl's docstrings appear to have been the victims of unresolved merge conflicts, e.g.: 

https://github.com/TuringLang/ParetoSmooth.jl/blob/698bb94c8cb0850b4a8861bbef6d17296e50b888/src/TuringHelpers.jl#L10-L16

**Comment by ParadaCarleton** [comment]
Got it, will fix in next PR.
