### ISSUE TITLE
Artefacts in smoothed weights

### ISSUE THREAD

**Issue by mschauer** [TuringLang/ParetoSmooth.jl#66]
I observed that when smoothing a tail
```
julia> M = collect(0:0.01:1.0).^10; M2 = copy(M); psis!(M2, tail_length=9); 

julia> plot([M M2])
```
<img width="636" alt="Screen Shot 2022-02-16 at 12 04 44" src="https://user-images.githubusercontent.com/1923437/154251819-6424cf34-3a8a-4dc6-bd69-83be977c1403.png">

the tail is not monotone increasing, as I would expect it to be. Isn't it constructed as sequence of quantiles?

**Comment by sethaxen** [comment]
PSIS fits a GPD distribution `d` to the extreme right tail of the log-weights (input values), and then replaces those values by uniformly-spaced quantiles from `d`. The location parameter of the GPD is set to the largest value not in the tail, so yes, it should be monotonically increasing.

e.g. a comparison with PSIS.jl:

```julia
using PSIS, ParetoSmooth

M = collect(0:0.01:1.0).^10
M2 = copy(M)
ParetoSmooth.psis!(M2)
M3 = copy(M)
PSIS.psis!(M3)
plot([M M2 M3]; legend=:topleft, label=["input" "ParetoSmooth" "PSIS"], xlims=(50, 100), alpha=0.75)
```
<img src=https://user-images.githubusercontent.com/8673634/154288378-2f59eb7f-091f-4f8f-be1a-45a052a2d75f.png width=500></img>

PSIS.jl and ParetoSmooth use the same algorithm, so to me this looks like a bug.

**Comment by mschauer** [comment]
The thing I find is that signature changed from the help, the following is outdated 
```
help?> psis!
search: psis! pushfirst! psis Psis psis_loo psis_ess PsisLoo PSIS

  psis!(is_ratios::AbstractVector{<:Real}; tail_length::Integer, log_ratios=false) -> Real
```
and we should use `log_ratios=false`. 

Then
```
using PSIS, ParetoSmooth

M = collect(0:0.01:1.0).^10
M2 = copy(M)
ParetoSmooth.psis!(M2, log_weights=false)
M3 = log.(M)
PSIS.psis!(M3)

plot([M M2 exp.(M3)]; legend=:topleft, linestyle=[:solid :dash :solid], label=["input" "ParetoSmooth" "PSIS"], color=[:blue :green :yellow], xlims=(50, Inf))
```


<img width="636" alt="Screen Shot 2022-02-16 at 16 04 58" src="https://user-images.githubusercontent.com/1923437/154292994-d9bd98f9-6cb8-4e7d-befc-f597053d2c59.png">

So this is a error in the docs
